dist: bionic
language: node_js
node_js:
  - '8'
  - '10'
# mono: latest 
addons:
  apt:
    packages:
      - unzip
      # - winehq-stable
      # - gnupg 
      # - ca-certificates
      
services:
  - xvfb

install:
  - wget https://raw.githubusercontent.com/project-nessus/TwitchAOT/develop/travis_mw.sh && sudo chmod 775 travis_mw.sh
  - ./travis_mw.sh
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
  - npm install
  - sudo npm install -g electron-packager
 
script:
  - npm run ci
  - electron-packager . TwitchAOT --icon=twitch.ico --app-version=1.0.0 --app-bundle-id=twitchaot --platform win32 --arch x64 --out dist/ --overwrite
  - npm run build
  - npm run pack
  - npm run linux-build
  - npm run linux-pack
