dist: bionic
language: node_js
node_js:
  - '8'
  - '10'
mono:
  - latest
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
        key_url: 'https://dl.winehq.org/wine-builds/winehq.key'
    packages:
      - xvfb
      - gnupg 
      - ca-certificates 
      - unzip
      - winehp-stable
services:
  - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
  - npm install
 
script:
  - npm run ci
  - npm run linux-build
  - npm run pack
